podTemplate(yaml: '''
    apiVersion: v1
    kind: Pod
    spec:
      containers:
      - name: cloud-sdk
        image: google/cloud-sdk
        command:
        - sleep
        args:
        - 9999999
        volumeMounts:
        - name: shared-storage
          mountPath: /mnt
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
      restartPolicy: Never
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: jenkins-pv-claim
      - name: google-cloud-key
        secret:
          secretName: sdk-key
''') {
node(POD_LABEL) {
    stage('Deploying to prod') {
      git 'https://github.com/cassandrareed26/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git'
      container('cloud-sdk') {
        stage('Build a gradle project') {
          sh '''
          echo 'namespaces in the staging environment'
          kubectl get ns
          gcloud config set project umls23-381502
          gcloud auth login --cred-file=$GOOGLE_APPLICATION_CREDENTIALS
          echo 'namespaces in the prod environment'
          kubectl get ns
          cd Chapter08/sample1
          chmod +x gradlew
          ./gradlew smokeTest
          '''
        }
      }
    }
}
}
