podTemplate(yaml: '''
    apiVersion: v1
    kind: Pod
    spec:
      containers:
      - name: centos
        image: centos
        command:
        - sleep
        args:
        - 99d
      restartPolicy: Never
''') {
  node(POD_LABEL) {
    stage('k8s') {
      git 'https://github.com/cassandrareed26/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git'
      container('centos') {
        stage('start calculator') {
          sh '''
          cd Chapter08/sample1
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          ./kubectl delete deployment calculator-deployment
          ./kubectl delete service calculator-service
          ./kubectl delete deployment hazelcast
          ./kubectl delete service hazelcast
          sleep 20
          ./kubectl apply -f calculator.yaml
          ./kubectl apply -f hazelcast.yaml
          sleep 45
          '''
        }
        stage('run tests') {
            sh '''
            test $(curl calculator-service:8080/sum?a=6\\&b=2) -eq 8 && echo 'pass' || 'fail'
            test $(curl calculator-service:8080/div?a=6\\&b=2) -eq 3 && echo 'pass' || 'fail'
            '''
        }
      }
    }
  }
}
